### ISSUE TITLE
Usa el método css de jQuery, no JS

### ISSUE THREAD

**Issue by lmagarin** [javiloji/ReEntregaMastermindJquery#12]
https://github.com/javiloji/ReEntregaMastermindJquery/blob/bdb3b70a026e782619ed899f3c9d8f9ea337074e/js/main.js#L69
Revisa el resto

**Comment by javiloji** [comment]
La verdad es que lo puse asi porque no sabia ponerlo con jquery, porque estoy recorriendo el array arrayNegrosYBlancos que es un objeto javascript, entonces no me deja recorrerlo como un objeto jquery ni usar los metodos jquery para manejarlo, ¿que podria hacer?
