### ISSUE TITLE
Evita el uso del for y usa jQuery y los selectores.

### ISSUE THREAD

**Issue by lmagarin** [javiloji/ReEntregaMastermindJquery#4]
https://github.com/javiloji/ReEntregaMastermindJquery/blob/8632510eba9ef185d817d0c0fd5c29b2cfc2638d/js/main.js#L59
Debes usar jQuery. Selecciona donde tienes que pintar
    
   ```
 let resultados = masterMind.comprobar(getCombinacion());
        pintaEnHueco($divResultados.slice(0, resultados.enSuSitio), NEGRO);
        pintaEnHueco($divResultados.slice(resultados.enSuSitio, resultados.enSuSitio + resultados.esta), BLANCO);
```

y usa jQuery para cambiar el background DESDE JQUERY
`$huecoLibre.css("background", color);`

**Comment by javiloji** [comment]
Lourdes cada vez que intento usar css en una expresion como esta:

$((".colorComprobado")[i]).css("background","rgb(0,0,0)");

Me da error y no entiendo por que, no se usar Jquery correctamente

**Comment by lmagarin** [comment]
Hola Javi. Entiendo que este comentario es anterior a nuestra conversación. ¿Lo has revisado?
Estoy corrigiendo todos para mañana lunes, pero el tuyo no está actualizado, no?
